export const categories = ["Todos", "Alimentos", "Juguetes", "Spa", "Ropa", "Camas"];

export const products = [
  { id: 1, name: "Croquetas de Salmón Premium", price: 45.00, rating: 4.8, category: "Alimentos", petType: "Perro", stock: 15, emoji: "🐟", color: "bg-blue-100" },
  { id: 2, name: "Pelota KONG Goma Extra Resistente", price: 15.50, rating: 4.9, category: "Juguetes", petType: "Perro", stock: 8, emoji: "🎾", color: "bg-orange-100" },
  { id: 3, name: "Shampoo de Avena y Miel", price: 12.00, rating: 4.5, category: "Spa", petType: "Ambos", stock: 20, emoji: "🧴", color: "bg-teal-100" },
  { id: 4, name: "Hueso Dental de Calcio", price: 8.99, rating: 4.7, category: "Alimentos", petType: "Perro", stock: 50, emoji: "🦴", color: "bg-amber-100" },
  { id: 5, name: "Correa Neón Pro Nocturna", price: 22.00, rating: 4.6, category: "Ropa", petType: "Perro", stock: 5, emoji: "🦮", color: "bg-green-100" },
  { id: 6, name: "Cama Nube Relax L", price: 65.00, rating: 5.0, category: "Camas", petType: "Ambos", stock: 3, emoji: "☁️", color: "bg-sky-100" },
  { id: 7, name: "Suéter Invierno Azul Lana", price: 28.00, rating: 4.8, category: "Ropa", petType: "Perro", stock: 12, emoji: "🧥", color: "bg-rose-100" },
  { id: 8, name: "Ratón a Motor Turbo", price: 18.50, rating: 4.9, category: "Juguetes", petType: "Gato", stock: 10, emoji: "🐁", color: "bg-purple-100" },
];

// ─── MOCK: Usuarios (Supabase: tabla `users` / `profiles`) ───────────────────
// Preparado para mapear 1:1 con la respuesta de supabase.from('profiles').select(*)
export const mockUsers = [
  {
    id: 'u1',
    nombre_completo: 'Carlos Roberto R.',
    rol: 'cliente',
    telefono: '+591 70012345',
    email: 'carlos@mail.com',
    avatar_seed: 'Carlos',
    puntos_lealtad: 1240,
    ci: '10293847',
    direccion: 'Av. Principal #123, Edificio Bubble',
    created_at: '2024-01-15T10:00:00Z',
  },
  {
    id: 'u2',
    nombre_completo: 'Marta Sánchez',
    rol: 'cliente',
    telefono: '+591 65098765',
    email: 'marta.s@web.com',
    avatar_seed: 'Marta',
    puntos_lealtad: 450,
    ci: '87654321',
    direccion: 'Calle Sucre #456, Piso 3',
    created_at: '2024-02-20T14:30:00Z',
  },
  {
    id: 'u3',
    nombre_completo: 'Elena Silva',
    rol: 'groomer',
    telefono: '+591 71022334',
    email: 'elena.g@bubble.com',
    avatar_seed: 'Elena',
    puntos_lealtad: 0,
    ci: '56473829',
    direccion: 'Interna Bubble Pet Spa',
    created_at: '2023-11-01T09:00:00Z',
  },
  {
    id: 'u5',
    nombre_completo: 'Mario Admin',
    rol: 'admin',
    telefono: '+591 7224455',
    email: 'mario@spa.com',
    avatar_seed: 'Mario',
    puntos_lealtad: 0,
    ci: '112233',
    direccion: 'Oficina Central',
    created_at: '2023-09-10T08:00:00Z',
  },
  {
    id: 'u6',
    nombre_completo: 'Ana Recepción',
    rol: 'recepcion',
    telefono: '+591 6655443',
    email: 'ana@spa.com',
    avatar_seed: 'Ana',
    puntos_lealtad: 0,
    ci: '554433',
    direccion: 'Centro Histórico',
    created_at: '2023-10-05T08:00:00Z',
  },
  {
    id: 'u4',
    nombre_completo: 'Diego Flores',
    rol: 'cliente',
    telefono: '+591 72034521',
    email: 'diego.f@email.com',
    avatar_seed: 'Diego',
    puntos_lealtad: 870,
    ci: '29384756',
    direccion: 'Zona Sur, Calacoto #890',
    created_at: '2024-03-10T11:00:00Z',
  },
];

// ─── MOCK: Mascotas (Supabase: tabla `mascotas`) ──────────────────────────────
// owner_id = FK a users.id
export const mockPets = [
  {
    id: 'm1',
    owner_id: 'u1',
    nombre: 'Killer',
    especie: 'Perro',
    raza: 'Golden Retriever',
    tamano: 'Grande',
    temperamento: 'Es un perro muy amigable pero odia que le toquen las patas delanteras. Necesita paciencia al principio.',
    alergias: ['Avena', 'Pollo', 'Perfumes'],
    foto: '🦮',
    ultima_visita: '2024-10-12',
    servicio_ultima_visita: 'Baño & Corte',
  },
  {
    id: 'm2',
    owner_id: 'u1',
    nombre: 'Luna',
    especie: 'Gato',
    raza: 'Siamés',
    tamano: 'Pequeño',
    temperamento: 'Gata muy nerviosa con extraños. Se recomienda usar Feliway antes de la sesión de spa.',
    alergias: ['Pescado Azul'],
    foto: '🐈⬛',
    ultima_visita: '2024-09-05',
    servicio_ultima_visita: 'Baño Especial',
  },
  {
    id: 'm3',
    owner_id: 'u2',
    nombre: 'Coco',
    especie: 'Perro',
    raza: 'Poodle',
    tamano: 'Pequeño',
    temperamento: 'Muy calmado y colaborador durante el grooming. Le encanta la atención.',
    alergias: [],
    foto: '🐩',
    ultima_visita: '2024-11-01',
    servicio_ultima_visita: 'Grooming Completo',
  },
  {
    id: 'm4',
    owner_id: 'u4',
    nombre: 'Max',
    especie: 'Perro',
    raza: 'Bulldog Francés',
    tamano: 'Mediano',
    temperamento: 'Max es extremadamente nervioso con el ruido del secador. Se recomienda bozal de canasta por precaución y secado manual. No usar fragancias cítricas.',
    alergias: ['Perfumes Cítricos', 'Avena'],
    foto: '🐶',
    ultima_visita: '2024-11-15',
    servicio_ultima_visita: 'Baño Medicado',
  },
];

// Pet asignado al groomer en turno activo (simulado)
export const groomerActivePet = mockPets.find((p) => p.id === 'm4');
