export const THEMES = {
  menta: {
    id: 'menta',
    name: 'Menta Ice',
    icon: '🍃',
    vars: {
      '--bg': '#F0F4F8',
      '--text': '#0f172a',
      '--border': '#0f172a',
      '--primary': '#14b8a6',
      '--secondary': '#fbbf24',
      '--shadow': '#0f172a',
      '--card': '#ffffff',
    },
  },
  chicle: {
    id: 'chicle',
    name: 'Pink Chicle',
    icon: '🍬',
    vars: {
      '--bg': '#FFF0F5',
      '--text': '#2D3748',
      '--border': '#2D3748',
      '--primary': '#FF69B4',
      '--secondary': '#00E5FF',
      '--shadow': '#2D3748',
      '--card': '#ffffff',
    },
  },
  cyber: {
    id: 'cyber',
    name: 'Cyber Pet',
    icon: '⚡',
    vars: {
      '--bg': '#EAE6FF',
      '--text': '#1A1025',
      '--border': '#1A1025',
      '--primary': '#8A2BE2',
      '--secondary': '#39FF14',
      '--shadow': '#1A1025',
      '--card': '#ffffff',
    },
  },
  arcade: {
    id: 'arcade',
    name: 'Retro Arcade',
    icon: '👾',
    vars: {
      '--bg': '#1A202C',
      '--text': '#F7FAFC',
      '--border': '#F7FAFC',
      '--primary': '#F6E05E',
      '--secondary': '#FF00FF',
      '--shadow': '#00E5FF',
      '--card': '#2D3748',
    },
  },
  sol: {
    id: 'sol',
    name: 'Golden Sol',
    icon: '☀️',
    vars: {
      '--bg': '#FFFBEB',
      '--text': '#78350F',
      '--border': '#78350F',
      '--primary': '#F59E0B',
      '--secondary': '#EF4444',
      '--shadow': '#78350F',
      '--card': '#ffffff',
    },
  },
  oceano: {
    id: 'oceano',
    name: 'Deep Sea',
    icon: '🌊',
    vars: {
      '--bg': '#F0FDFF',
      '--text': '#164E63',
      '--border': '#164E63',
      '--primary': '#06B6D4',
      '--secondary': '#FACC15',
      '--shadow': '#164E63',
      '--card': '#ffffff',
    },
  },
};
